AWSTemplateFormatVersion: 2010-09-09
Description: 'ALIS Route53 & CloudFront Resources for development.'

Parameters:
  AlisAppId:
    Type: String
  ApiApiGatewayId:
    Type: String
  FrontendApiGatewayId:
    Type: String
  Oauth2ApiGatewayId:
    Type: String
  Oauth2apiApiGatewayId:
    Type: String
  LaboApiGatewayId:
    Type: String
  AcmCertificateArn:
    Type: String
#  OaiForS3Bucket:
#    Type: String
#  DistS3BucketName:
#    Type: 'AWS::SSM::Parameter::Value<String>'

Resources:
  zonealistesttk:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Sub "${AlisAppId}.alis-test.tk."
  dnsalisstagingalistesttk:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref zonealistesttk
      RecordSets:
        - Name: !Sub "${AlisAppId}.alis-test.tk."
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt distd3gz5s641vhc5ucloudfrontnet.DomainName
  # FIXME: Oauth分？
  #  dnsoauth2alisstagingalistesttk:
  #    Type: 'AWS::Route53::RecordSetGroup'
  #    Properties:
  #      HostedZoneId: !Ref zonealistesttk
  #      RecordSets:
  #        - Name: oauth2!Sub "${AlisAppId}.alis-test.tk".
  #          Type: CNAME
  #          TTL: '60'
  #          ResourceRecords:
  #            - d1582tru02jlgw.cloudfront.net

  distd3gz5s641vhc5ucloudfrontnet:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "${AlisAppId}.alis-test.tk"
        Enabled: true
        PriceClass: PriceClass_200
        CacheBehaviors:
          - TargetOriginId: api
            PathPattern: /api/me/*
            ViewerProtocolPolicy: allow-all
            MinTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
              Cookies:
                Forward: all
          - TargetOriginId: api
            PathPattern: /api/articles/*/comments
            ViewerProtocolPolicy: allow-all
            MinTTL: 5
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          - TargetOriginId: api
            PathPattern: /api/articles/*/price
            ViewerProtocolPolicy: allow-all
            MinTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          - TargetOriginId: api
            PathPattern: /api/login/*
            ViewerProtocolPolicy: allow-all
            MinTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
          - TargetOriginId: api
            PathPattern: /api/sign_up/*
            ViewerProtocolPolicy: allow-all
            MinTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
          - TargetOriginId: api
            PathPattern: /api/*
            ViewerProtocolPolicy: allow-all
            MinTTL: 120
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
          - TargetOriginId: oauth2api
            PathPattern: /oauth2api/me/*
            ViewerProtocolPolicy: allow-all
            MinTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
              Cookies:
                Forward: all
          - TargetOriginId: oauth2api
            PathPattern: /oauth2api/*
            ViewerProtocolPolicy: allow-all
            MinTTL: 120
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
              Cookies:
                Forward: none
          - TargetOriginId: oauth2
            PathPattern: /oauth2/*
            ViewerProtocolPolicy: allow-all
            MinTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
              Cookies:
                Forward: none
#          - TargetOriginId: s3-dist
#            PathPattern: /d/api/*
#            ViewerProtocolPolicy: allow-all
#            MinTTL: 100
#            AllowedMethods:
#              - HEAD
#              - GET
#            CachedMethods:
#              - HEAD
#              - GET
#            ForwardedValues:
#              QueryString: true
#              Cookies:
#                Forward: none
#          - TargetOriginId: s3-dist
#            PathPattern: /d/*
#            ViewerProtocolPolicy: allow-all
#            MinTTL: 0
#            AllowedMethods:
#              - HEAD
#              - GET
#            CachedMethods:
#              - HEAD
#              - GET
#            ForwardedValues:
#              QueryString: false
#              Cookies:
#                Forward: none
          - TargetOriginId: frontend
            PathPattern: /*
            ViewerProtocolPolicy: redirect-to-https
            MinTTL: 120
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - GET
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
        DefaultCacheBehavior:
          TargetOriginId: frontend
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 120
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
        Origins:
          - DomainName: !Sub "${ApiApiGatewayId}.execute-api.ap-northeast-1.amazonaws.com"
            Id: api
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: https-only
          - DomainName: !Sub "${FrontendApiGatewayId}.execute-api.ap-northeast-1.amazonaws.com"
            Id: frontend
            OriginPath: /prod
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: https-only
#          - DomainName: !Sub "${DistS3BucketName}.s3.amazonaws.com"
#            Id: s3-dist
#            S3OriginConfig:
#              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OaiForS3Bucket}"
          - DomainName: !Sub "${Oauth2ApiGatewayId}.execute-api.ap-northeast-1.amazonaws.com"
            Id: oauth2
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: https-only
          - DomainName: !Sub "${Oauth2apiApiGatewayId}.execute-api.ap-northeast-1.amazonaws.com"
            Id: oauth2api
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: https-only
          - DomainName: !Sub "${LaboApiGatewayId}.execute-api.ap-northeast-1.amazonaws.com"
            Id: labo
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: https-only
        Restrictions:
          GeoRestriction:
            RestrictionType: none
            Locations: []
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016

