AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The databases for the ALIS application.

Resources:
  ArticleInfo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: N
        - AttributeName: sync_elasticsearch
          AttributeType: N
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-sort_key-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: user_id-sort_key-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: article_id-status_key-index
          KeySchema:
            - AttributeName: article_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: sync_elasticsearch-index
          KeySchema:
            - AttributeName: sync_elasticsearch
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  ArticleContent:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ArticleHistory:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
        - AttributeName: created_at
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  ArticleContentEdit:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ArticleAlisToken:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: evaluated_at
          AttributeType: N
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
        - AttributeName: evaluated_at
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: evaluated_at-index
          KeySchema:
            - AttributeName: evaluated_at
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  ArticleEvaluatedManage:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: type
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ArticleLikedUser:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: target_date
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: N
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: article_id-sort_key-index
          KeySchema:
            - AttributeName: article_id
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      GlobalSecondaryIndexes:
        - IndexName: target_date-sort_key-index
          KeySchema:
            - AttributeName: target_date
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  ArticlePvUser:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: target_date
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: N
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: article_id-sort_key-index
          KeySchema:
            - AttributeName: article_id
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      GlobalSecondaryIndexes:
        - IndexName: target_date-sort_key-index
          KeySchema:
            - AttributeName: target_date
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  ArticleScore:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: evaluated_at
          AttributeType: N
        - AttributeName: score
          AttributeType: N
      KeySchema:
        - AttributeName: evaluated_at
          KeyType: HASH
        - AttributeName: article_id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: evaluated_at-score-index
          KeySchema:
            - AttributeName: evaluated_at
              KeyType: HASH
            - AttributeName: score
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  ArticleTokenAggregation:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: evaluated_at
          AttributeType: N
        - AttributeName: article_id
          AttributeType: S
      KeySchema:
        - AttributeName: evaluated_at
          KeyType: HASH
        - AttributeName: article_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  LikeTokenAggregation:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleTokenAggregation
    Properties:
      AttributeDefinitions:
        - AttributeName: evaluated_at
          AttributeType: N
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: evaluated_at
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  ArticleFraudUser:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - ArticleInfo
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: sync_elasticsearch
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: sync_elasticsearch-index
          KeySchema:
            - AttributeName: sync_elasticsearch
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  BetaUsers:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Users
    Properties:
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ExternalProviderUsers:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Users
    Properties:
      AttributeDefinitions:
        - AttributeName: external_provider_user_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: external_provider_user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  Notification:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Users
    Properties:
      AttributeDefinitions:
        - AttributeName: notification_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: N
      KeySchema:
        - AttributeName: notification_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id-sort_key-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  UnreadNotificationManager:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Notification
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  Comment:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Users
    Properties:
      AttributeDefinitions:
        - AttributeName: comment_id
          AttributeType: S
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: N
        - AttributeName: parent_id
          AttributeType: S
      KeySchema:
        - AttributeName: comment_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: article_id-sort_key-index
          KeySchema:
            - AttributeName: article_id
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: parent_id-sort_key-index
          KeySchema:
            - AttributeName: parent_id
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  CommentLikedUser:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Comment
    Properties:
      AttributeDefinitions:
        - AttributeName: comment_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: article_id
          AttributeType: S
      KeySchema:
        - AttributeName: comment_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: article_id-index
          KeySchema:
            - AttributeName: article_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  DeletedComment:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Comment
    Properties:
      AttributeDefinitions:
        - AttributeName: comment_id
          AttributeType: S
      KeySchema:
        - AttributeName: comment_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  Topic:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Comment
    Properties:
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: order
          AttributeType: N
        - AttributeName: index_hash_key
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: index_hash_key-order-index
          KeySchema:
            - AttributeName: index_hash_key
              KeyType: HASH
            - AttributeName: order
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  Tag:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Comment
    Properties:
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  Tip:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Comment
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: N
        - AttributeName: uncompleted
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: uncompleted-index
          KeySchema:
            - AttributeName: uncompleted
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  ScreenedArticle:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: article_type
          AttributeType: S
      KeySchema:
        - AttributeName: article_type
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  UserFraud:
    Type: AWS::DynamoDB::Table
    DependsOn:
      - Tip
    Properties:
      AttributeDefinitions:
        - AttributeName: target_user_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: target_user_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  TokenDistribution:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: distribution_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: evaluated_at
          AttributeType: N
        - AttributeName: sort_key
          AttributeType: N
      KeySchema:
        - AttributeName: distribution_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id-sort_key-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: evaluated_at-index
          KeySchema:
            - AttributeName: evaluated_at
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  UserFirstExperience:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  Nonce:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: nonce
          AttributeType: S
      KeySchema:
        - AttributeName: nonce
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiration_time
        Enabled: true
      BillingMode: PAY_PER_REQUEST
  PaidArticles:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: N
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: article_id-user_id-index
          KeySchema:
            - AttributeName: article_id
              KeyType: HASH
            - AttributeName: user_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: user_id-sort_key-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: sort_key
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  TokenSend:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: N
        - AttributeName: uncompleted
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: uncompleted-index
          KeySchema:
            - AttributeName: uncompleted
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
