AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ElasticSearchService

Parameters:
  ApiLambdaRole:
    Type: 'AWS::SSM::Parameter::Value<String>'

Resources:
  ElasticSearchService:
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      AccessPolicies:
        !Sub
        - |-
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": "${ApiLambdaRole}"
                },
                "Action": "es:*",
                "Resource": "arn:aws:es:${Region}:${AccountId}:domain/${StackName}/*"
              }
            ]
          }
        - {
          ApiLambdaRole: !Ref ApiLambdaRole,
          Region: !Ref 'AWS::Region',
          AccountId: !Ref 'AWS::AccountId',
          StackName: !Ref 'AWS::StackName'
        }
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      DomainName: !Ref "AWS::StackName"
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 35
      ElasticsearchClusterConfig:
        InstanceType: t2.medium.elasticsearch
        InstanceCount: 2
        DedicatedMasterEnabled: true
        ZoneAwarenessEnabled: false
        DedicatedMasterType: t2.medium.elasticsearch
        DedicatedMasterCount: 3
      ElasticsearchVersion: '6.2'
      SnapshotOptions:
        AutomatedSnapshotStartHour: 0
