AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda functions and API Gateway resources for the ALIS application.

Parameters:
  AlisAppId:
    Type: String
  ArticleInfoTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
  ArticleContentEditHistoryTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
  UsersTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
  UserConfigurationsTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
  TopicTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
  ElasticSearchEndpoint:
    Type: 'AWS::SSM::Parameter::Value<String>'
  PrivateChainAwsAccessKey:
    Type: 'AWS::SSM::Parameter::Value<String>'
  PrivateChainAwsSecretAccessKey:
    Type: 'AWS::SSM::Parameter::Value<String>'
  PrivateChainExecuteApiHost:
    Type: 'AWS::SSM::Parameter::Value<String>'
  SucceededTipTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
  NotificationTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
  UnreadNotificationManagerTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
  ScreenedArticleTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
  CognitoUserPoolId:
    Type: 'AWS::SSM::Parameter::Value<String>'
  CognitoIdentityPoolId:
    Type: 'AWS::SSM::Parameter::Value<String>'
  AllTokenHistoryCsvDownloadS3Bucket:
    Type: 'AWS::SSM::Parameter::Value<String>'
  PrivateChainOperationUrl:
    Type: 'AWS::SSM::Parameter::Value<String>'
  PrivateChainAlisTokenAddress:
    Type: 'AWS::SSM::Parameter::Value<String>'
  PrivateChainBridgeAddress:
    Type: 'AWS::SSM::Parameter::Value<String>'
  BurnAddress:
    Type: 'AWS::SSM::Parameter::Value<String>'

Resources:

  #  Functions

  ArticleSupportersIndex:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/articles_supporters_index.zip
      Environment:
        Variables:
          ARTICLE_INFO_TABLE_NAME: !Ref ArticleInfoTableName
          SUCCEEDED_TIP_TABLE_NAME: !Ref SucceededTipTableName
          USERS_TABLE_NAME: !Ref UsersTableName
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 300
      TracingConfig:
        Mode: "Active"
  ArticlesTipRanking:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/articles_tip_ranking.zip
      Environment:
        Variables:
          TOPIC_TABLE_NAME: !Ref TopicTableName
          SCREENED_ARTICLE_TABLE_NAME: !Ref ScreenedArticleTableName
          ELASTIC_SEARCH_ENDPOINT: !Ref ElasticSearchEndpoint
          PRIVATE_CHAIN_AWS_SECRET_ACCESS_KEY: !Ref PrivateChainAwsSecretAccessKey
          PRIVATE_CHAIN_EXECUTE_API_HOST: !Ref PrivateChainExecuteApiHost
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 300
      TracingConfig:
        Mode: "Active"
  MeArticlesContentEditHistoriesIndex:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_articles_content_edit_histories_index.zip
      Environment:
        Variables:
          ARTICLE_INFO_TABLE_NAME: !Ref ArticleInfoTableName
          ARTICLE_CONTENT_EDIT_HISTORY_TABLE_NAME: !Ref ArticleContentEditHistoryTableName
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 300
      TracingConfig:
        Mode: "Active"
  MeArticlesDraftsDelete:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_articles_drafts_delete.zip
      Environment:
        Variables:
          ARTICLE_INFO_TABLE_NAME: !Ref ArticleInfoTableName
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 300
      TracingConfig:
        Mode: "Active"
  MeConfigurationsMuteUsersAdd:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_configurations_mute_users_add.zip
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTableName
          USER_CONFIGURATIONS_TABLE_NAME: !Ref UserConfigurationsTableName
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 300
      TracingConfig:
        Mode: "Active"
  MeConfigurationsMuteUsersDelete:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_configurations_mute_users_delete.zip
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTableName
          USER_CONFIGURATIONS_TABLE_NAME: !Ref UserConfigurationsTableName
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 300
      TracingConfig:
        Mode: "Active"
  MeConfigurationsMuteUsersIndex:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_configurations_mute_users_index.zip
      Environment:
        Variables:
          USER_CONFIGURATIONS_TABLE_NAME: !Ref UserConfigurationsTableName
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 300
      TracingConfig:
        Mode: "Active"
  MeConfigurationsWalletAdd:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_configurations_wallet_add.zip
      Environment:
        Variables:
          USER_CONFIGURATIONS_TABLE_NAME: !Ref UserConfigurationsTableName
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          PRIVATE_CHAIN_OPERATION_URL: !Ref PrivateChainOperationUrl
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 300
      TracingConfig:
        Mode: "Active"
  MeConfigurationsWalletShow:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_configurations_wallet_show.zip
      Environment:
        Variables:
          USER_CONFIGURATIONS_TABLE_NAME: !Ref UserConfigurationsTableName
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 300
      TracingConfig:
        Mode: "Active"
  MeWalletTokenAllhistoriesCreate:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_wallet_token_allhistories_create.zip
      Environment:
        Variables:
          NOTIFICATION_TABLE_NAME: !Ref NotificationTableName
          UNREAD_NOTIFICATION_MANAGER_TABLE_NAME: !Ref UnreadNotificationManagerTableName
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_IDENTITY_POOL_ID: !Ref CognitoIdentityPoolId
          PRIVATE_CHAIN_ALIS_TOKEN_ADDRESS: !Ref PrivateChainAlisTokenAddress
          PRIVATE_CHAIN_OPERATION_URL: !Ref PrivateChainOperationUrl
          PRIVATE_CHAIN_BRIDGE_ADDRESS: !Ref PrivateChainBridgeAddress
          ALL_TOKEN_HISTORY_CSV_DOWNLOAD_S3_BUCKET: !Ref AllTokenHistoryCsvDownloadS3Bucket
          BURN_ADDRESS: !Ref BurnAddress
          USER_CONFIGURATIONS_TABLE_NAME: !Ref UserConfigurationsTableName
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 900
      TracingConfig:
        Mode: "Active"
  MeWalletAllowanceShow:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_wallet_allowance_show.zip
      Environment:
        Variables:
          PRIVATE_CHAIN_BRIDGE_ADDRESS: !Ref PrivateChainBridgeAddress
          PRIVATE_CHAIN_EXECUTE_API_HOST: !Ref PrivateChainExecuteApiHost
          PRIVATE_CHAIN_AWS_ACCESS_KEY: !Ref PrivateChainAwsAccessKey
          PRIVATE_CHAIN_AWS_SECRET_ACCESS_KEY: !Ref PrivateChainAwsSecretAccessKey
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 900
      TracingConfig:
        Mode: "Active"
  MeWalletNonceShow:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/me_wallet_nonce_show.zip
      Environment:
        Variables:
          PRIVATE_CHAIN_EXECUTE_API_HOST: !Ref PrivateChainExecuteApiHost
          PRIVATE_CHAIN_AWS_ACCESS_KEY: !Ref PrivateChainAwsAccessKey
          PRIVATE_CHAIN_AWS_SECRET_ACCESS_KEY: !Ref PrivateChainAwsSecretAccessKey
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 900
      TracingConfig:
        Mode: "Active"
  UsersArticlesPopular:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/users_articles_popular.zip
      Environment:
        Variables:
          ARTICLE_INFO_TABLE_NAME: !Ref ArticleInfoTableName
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 900
      TracingConfig:
        Mode: "Active"
  UsersWalletAddressShow:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/users_wallet_address_show.zip
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 900
      TracingConfig:
        Mode: "Active"
  TopicsCryptoRankingIndex:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ./deploy/topics_crypto_ranking_index.zip
      Handler: handler.lambda_handler
      MemorySize: 3008
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LambdaRole"
      Runtime: python3.6
      Timeout: 15
      TracingConfig:
        Mode: "Active"

Outputs:
  ArticleSupportersIndex:
    Value: !GetAtt ArticleSupportersIndex.Arn
    Export:
      Name: !Sub "${AlisAppId}-ArticleSupportersIndex"
  ArticlesTipRanking:
    Value: !GetAtt ArticlesTipRanking.Arn
    Export:
      Name: !Sub "${AlisAppId}-ArticlesTipRanking"
  MeArticlesContentEditHistoriesIndex:
    Value: !GetAtt MeArticlesContentEditHistoriesIndex.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeArticlesContentEditHistoriesIndex"
  MeArticlesDraftsDelete:
    Value: !GetAtt MeArticlesDraftsDelete.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeArticlesDraftsDelete"
  MeConfigurationsMuteUsersAdd:
    Value: !GetAtt MeConfigurationsMuteUsersAdd.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeConfigurationsMuteUsersAdd"
  MeConfigurationsMuteUsersDelete:
    Value: !GetAtt MeConfigurationsMuteUsersDelete.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeConfigurationsMuteUsersDelete"
  MeConfigurationsMuteUsersIndex:
    Value: !GetAtt MeConfigurationsMuteUsersIndex.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeConfigurationsMuteUsersIndex"
  MeConfigurationsWalletAdd:
    Value: !GetAtt MeConfigurationsWalletAdd.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeConfigurationsWalletAdd"
  MeConfigurationsWalletShow:
    Value: !GetAtt MeConfigurationsWalletShow.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeConfigurationsWalletShow"
  MeWalletTokenAllhistoriesCreate:
    Value: !GetAtt MeWalletTokenAllhistoriesCreate.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeWalletTokenAllhistoriesCreate"
  MeWalletAllowanceShow:
    Value: !GetAtt MeWalletAllowanceShow.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeWalletAllowanceShow"
  MeWalletNonceShow:
    Value: !GetAtt MeWalletNonceShow.Arn
    Export:
      Name: !Sub "${AlisAppId}-MeWalletNonceShow"
  UsersWalletAddressShow:
    Value: !GetAtt UsersWalletAddressShow.Arn
    Export:
      Name: !Sub "${AlisAppId}-UsersWalletAddressShow"
  UsersArticlesPopular:
    Value: !GetAtt UsersArticlesPopular.Arn
    Export:
      Name: !Sub "${AlisAppId}-UsersArticlesPopular"
  TopicsCryptoRankingIndex:
    Value: !GetAtt TopicsCryptoRankingIndex.Arn
    Export:
      Name: !Sub "${AlisAppId}-TopicsCryptoRankingIndex"
