AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda functions and API Gateway resources for the ALIS application.

Parameters:
  RestApiArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
  AlisAppId:
    Type: String

Resources:
  LoginYahooAuthorizationUrlApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LoginYahooAuthorizationUrl"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/login/yahoo/authorization_url
  LoginYahooApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LoginYahoo"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/POST/login/yahoo
  LoginFacebookAuthorizationUrlApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LoginFacebookAuthorizationUrl"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/login/facebook/authorization_url
  LoginFacebookApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-LoginFacebook"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/POST/login/facebook
  ArticlesPriceShowApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-ArticlesPriceShow"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/articles/*/price
  ArticlesSupportersIndexApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-ArticleSupportersIndex"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/articles/*/supporters
  MeArticlesPurchasedArticleIdsIndexApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeArticlesPurchasedArticleIdsIndex"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/me/articles/purchased/article_ids
  MeArticlesPurchasedShowApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeArticlesPurchasedShow"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/me/articles/purchased/*
  MeArticlesPurchasedIndexApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeArticlesPurchasedIndex"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/me/articles/purchased
  MeArticlesPurchaseApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeArticlesPurchaseCreate"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/POST/me/articles/*/purchase
  MeWalletTokenHistoriesIndexApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeWalletTokenHistoriesIndex"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/me/wallet/token/histories
  MeWalletTokenSendApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeWalletTokenSend"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/POST/me/wallet/token/send
  WalletBridgeInformationShowApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-WalletBridgeInformationShow"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/wallet/bridge_information
  ArticlesTipRankingApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-ArticlesTipRanking"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/articles/tip_ranking
  MeApplicationsIndexApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeApplicationsIndex"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/me/applications
  MeApplicationsShowApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeApplicationsShow"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/me/applications/*
  MeApplicationsCreateApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeApplicationsCreate"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/POST/me/applications
  MeApplicationsUpdateApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeApplicationsUpdate"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/PUT/me/applications/*
  MeApplicationsDeleteApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeApplicationsDelete"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/DELETE/me/applications/*
  MeAllowedApplicationsIndexApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeAllowedApplicationsIndex"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/me/allowed_applications
  MeAllowedApplicationsDeleteApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeAllowedApplicationsDelete"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/DELETE/me/allowed_applications
  ApplicationsShowApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-ApplicationsShow"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/applications/*
  MeArticlesContentEditHistoriesIndexApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::ImportValue:
          Fn::Sub: "${AlisAppId}-MeArticlesContentEditHistoriesIndex"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub ${RestApiArn}/*/GET/me/articles/*/content_edit_histories
