swagger: "2.0"
info:
  title:
    Ref: "AWS::StackName"
  version: 1.0.0
basePath: /
schemes:
  - https
definitions:
  Topic:
    type: object
    properties:
      name:
        type: string
      display_name:
        type: string
      order:
        type: integer
      index_hash_key:
        type: string
paths:
  /topics:
    get:
      description: トピックの一覧を取得
      responses:
        '200':
          description: トピックの一覧
          schema:
            type: array
            items:
              $ref: '#/definitions/Topic'
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
        uri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TopicsIndex.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
    security:
      - CustomAuthorizer: []
securityDefinitions:
  CustomAuthorizer:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: custom
    x-amazon-apigateway-authorizer:
      type: token
      authorizerUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Authorizer.Arn}/invocations
      authorizerCredentials:
        Fn::Sub: ${ApiGatewayAuthorizerRole.Arn}
