version: 2.1

references:
  setup_remote_docker: &setup_remote_docker
    setup_remote_docker:
      version: 17.11.0-ce

jobs:
  main:
    docker:
      - image: circleci/python:3.6.1
      - image: bluszcz/bflocalstack-dynamodb-s3
      - image: alismedia/dynamodb-local
        environment:
          MAX_HEAP_SIZE: 2048m
          HEAP_NEWSIZE: 512m
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
        environment:
          discovery.type: single-node

    working_directory: /tmp/repo

    steps:
      - checkout

      - <<: *setup_remote_docker

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_test.txt" }}
            - v3-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_test.txt

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_test.txt" }}

      - run:
          name: run checkstyle for python code
          command: |
            . venv/bin/activate
            pycodestyle src tests ./*.py

      - run:
          name: run pyflakes for python code
          command: |
            . venv/bin/activate
            pyflakes src tests ./*.py

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # 全テスト実行
             python exec_test.py

      - run:
          name: make deploy package
          command: |
            . venv/bin/activate
            ./packaging.sh

      - run:
          name: run deploy
          command: |
            if [ $ALIS_APP_ID ]; then
              . venv/bin/activate
              ./deploy_api.sh
            fi

            if [ $SERVERLESS_REST_API_ID ]; then
              ./fix_api.sh
            fi

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - persist_to_workspace:
          root: /tmp/repo/deploy
          paths:
            - articles_random.zip

  labo:
    docker:
      - image: circleci/node:12.4.0

    working_directory: /tmp/repo

    steps:
      - checkout

      - attach_workspace:
          at: /tmp/repo/deploy

      - restore_cache:
          keys:
            - v1-npm-dependencies-{{ checksum "package-lock.json" }}
            - v1-npm-dependencies-

      - run:
          command: npm i

      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Deployment
          command: |
            if [ $ALIS_APP_ID ]; then
              npm run deploy
            fi

workflows:
  build-deploy:
    jobs:
      - main
      - labo:
          requires:
            - main
