version: 2

references:
    setup_remote_docker: &setup_remote_docker
      setup_remote_docker:
        version: 17.11.0-ce

jobs:
  build:

    docker:
      - image: circleci/python:3.6.1
      - image: localstack/localstack

    working_directory: ~/repo

    steps:
      - checkout
      - <<: *setup_remote_docker
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_test.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run checkstyle for python code
          command: |
            . venv/bin/activate
            pycodestyle src tests ./*.py

      - run:
          name: make deploy package
          command: |
            docker image build --tag deploy-image .
            docker container run -it --name deploy-container deploy-image
            docker container cp deploy-container:/workdir/vendor-package .
            . venv/bin/activate
            python make_deploy_zip.py

      - run:
          name: run deploy
          command: |
            . venv/bin/activate
            python make_template.py
            aws cloudformation package \
              --template-file template.yaml \
              --s3-bucket $DEPLOY_BUCKET_NAME \
              --output-template-file packaged-template.yaml
            aws cloudformation deploy \
              --template-file packaged-template.yaml \
              --stack-name $CLOUDFORMATION_STACK_NAME \
              --capabilities CAPABILITY_IAM

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # 全テスト実行
            python exec_test.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
