version: 2.1

references:
  setup_remote_docker: &setup_remote_docker
    setup_remote_docker:
      version: 17.11.0-ce

executors:
  python3_6_1:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.1

commands:
  prepare-resources:
    parameters:
      resource:
        type: string
        default: 'requirements.txt'
    steps:
      - checkout

      - <<: *setup_remote_docker

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "<< parameters.resource >>" }}
            - v3-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r << parameters.resource >>

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "<< parameters.resource >>" }}

  deploy:
    parameters:
      target:
        type: string
    steps:
      - prepare-resources

      - attach_workspace:
          at: .

      - run:
          name: Deployment
          command: |
            if [ $ALIS_APP_ID ]; then
              . venv/bin/activate
              ./deploy.sh << parameters.target >>
            fi

jobs:
  lint:
    executor:
      name: python3_6_1

    steps:
      - prepare-resources:
          resource: 'requirements_test.txt'

      - run:
          name: checkstyle
          command: |
            . venv/bin/activate
            pycodestyle src tests ./*.py

      - run:
          name: pyflakes
          command: |
            . venv/bin/activate
            pyflakes src tests ./*.py

  test:
    docker:
      - image: circleci/python:3.6.1
      - image: bluszcz/bflocalstack-dynamodb-s3
      - image: alismedia/dynamodb-local
        environment:
          MAX_HEAP_SIZE: 2048m
          HEAP_NEWSIZE: 512m
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
        environment:
          discovery.type: single-node

    working_directory: ~/repo

    steps:
      - checkout

      - <<: *setup_remote_docker

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_test.txt" }}
            - v3-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_test.txt

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_test.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # 全テスト実行
            python exec_test.py

      - store_artifacts:
          path: test-reports
          destination: test-reports

  packaging:
    executor:
      name: python3_6_1

    steps:
      - prepare-resources

      - run:
          name: make deploy package
          command: |
            . venv/bin/activate
            ./packaging.sh

      - persist_to_workspace:
          root: .
          paths:
            - deploy/*

  deploy-function:
    executor:
      name: python3_6_1

    steps:
      - deploy:
          target: 'function'

  deploy-api:
    executor:
      name: python3_6_1

    steps:
      - deploy:
          target: 'api'

  deploy-permission:
    executor:
      name: python3_6_1

    steps:
      - deploy:
          target: 'permission'

  labo:
    docker:
      - image: circleci/node:12.4.0

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: .

      - restore_cache:
          keys:
            - v1-npm-dependencies-{{ checksum "package-lock.json" }}
            - v1-npm-dependencies-

      - run:
          command: npm i

      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Deployment
          command: |
            if [ $ALIS_APP_ID ]; then
              npm run deploy
            fi

workflows:
  build-deploy:
    jobs:
      - lint
      - test
      - packaging
      - deploy-function:
          requires:
            - lint
            - test
            - packaging
      - deploy-api:
          requires:
            - lint
            - test
            - packaging
      - deploy-permission:
          requires:
            - deploy-function
            - deploy-api
      - labo:
          requires:
            - deploy-function
            - deploy-api
