version: 2

references:
    setup_remote_docker: &setup_remote_docker
      setup_remote_docker:
        version: 17.11.0-ce

jobs:
  build:

    docker:
      - image: circleci/python:3.6.1
      - image: bluszcz/bflocalstack-dynamodb-s3
      - image: alismedia/dynamodb-local
        environment:
          MAX_HEAP_SIZE: 2048m
          HEAP_NEWSIZE: 512m
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
        environment:
          discovery.type: single-node

    working_directory: ~/repo

    steps:
      - checkout
      - <<: *setup_remote_docker
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "requirements.txt" }}
          - v3-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_test.txt

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run checkstyle for python code
          command: |
            . venv/bin/activate
            pycodestyle src tests ./*.py

      - run:
          name: run pyflakes for python code
          command: |
            . venv/bin/activate
            pyflakes src tests ./*.py

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # 全テスト実行
            python exec_test.py

      - run:
          name: make deploy package
          command: |
            if [ $ALIS_APP_ID ]; then
              docker image build --tag deploy-image .
              docker container run -it --name deploy-container deploy-image
              docker container cp deploy-container:/workdir/vendor-package .
              . venv/bin/activate
              python make_deploy_zip.py
            fi

      - run:
          name: run deploy
          command: |
            if [ $ALIS_APP_ID ]; then
              . venv/bin/activate
              ./deploy.sh api
            fi

      - store_artifacts:
          path: test-reports
          destination: test-reports
